import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { LogoutButton } from "./logout-button";
import { StatusPill, ZainMark } from "../zain-mark";

export default async function DashboardPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: pals } = await supabase.from("pals").select("id, name, short_description, tavus_pal_id").eq("owner_id", user.id).order("created_at", { ascending: false });
  return <main className="zain-shell min-h-screen text-zain-ink"><div className="mx-auto max-w-6xl px-5 py-5 md:px-8"><header className="glass-panel flex flex-wrap items-center justify-between gap-4 rounded-2xl px-4 py-3"><div className="flex items-center gap-4"><ZainMark /><StatusPill>PAL mesh active</StatusPill></div><div className="flex items-center gap-3"><Link href="/" className="button-secondary text-sm">Start video conversation</Link><LogoutButton /></div></header><section className="mt-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow mb-3">Spatial mesh / persona cluster</p><h1 className="font-display text-4xl font-semibold tracking-tight">PAL management</h1><p className="mt-2 max-w-2xl text-zain-muted">Configure, monitor, and deploy autonomous video sales personas.</p></div><Link href="/dashboard/pals/new" className="button-primary">Deploy new PAL <span aria-hidden="true" className="ml-2">+</span></Link></section><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active PALs" value={String(pals?.length ?? 0)} detail="Ready across your workspace" /><Metric label="Connection state" value="Live" detail="PAL mesh synchronized" /><Metric label="Response loop" value="112ms" detail="Target neural latency" /><Metric label="Workspace" value="Secure" detail="Authenticated console" /></section><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{pals?.length ? pals.map((pal) => <Link key={pal.id} href={`/dashboard/pals/${pal.id}`} className="glass-panel group rounded-2xl p-5 transition hover:-translate-y-0.5 hover:border-zain-sage/60"><div className="flex items-start justify-between gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-zain-raised font-display text-lg text-zain-sageLight">{pal.name.slice(0, 1).toUpperCase()}</div><StatusPill>Active persona</StatusPill></div><h2 className="mt-5 font-display text-xl font-semibold">{pal.name}</h2><p className="mt-1 min-h-10 text-sm leading-5 text-zain-muted">{pal.short_description || pal.tavus_pal_id}</p><div className="mt-5 flex items-center justify-between border-t border-white/5 pt-4 font-mono text-[11px] text-zain-sageLight"><span>CONFIGURED</span><span aria-hidden="true">→</span></div></Link>) : <div className="glass-panel rounded-2xl p-8 text-zain-muted md:col-span-2 xl:col-span-3">No PALs yet. Deploy your first persona to start the mesh.</div>}</div></div></main>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="glass-panel rounded-xl p-4"><p className="eyebrow text-[10px] text-zain-muted">{label}</p><p className="mt-4 font-display text-3xl font-semibold">{value}</p><p className="mt-2 text-sm text-zain-muted">{detail}</p></div>; }
